POST http://localhost:3000/users/register
Content-Type: application/json

{
  "user": "Carlos",
  "email": "patoto@gmail.com",
  "password": "300056"
}
###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "patoto@gmail.com",
  "password": "300056"
}
###

GET  http://localhost:3000/users/logout
Content-Type: application/json

###
GET  http://localhost:3000/products
Content-Type: application/json

###

POST http://localhost:3000/invoice/create
Content-Type: application/json

{
  "clientName": "Carlos", 
  "food": "Caesar Salad", 
  "cant": "3"
}

###


